/**
 * Demo dataset.
 *
 * The backend (FastAPI + Postgres per the PRD) is not connected yet, so the
 * application reads from this in-memory dataset. Shapes match `types.ts`, so
 * each accessor below can be replaced by an API call one-for-one.
 */

import type {
  ActivityItem,
  AuditRecord,
  Campaign,
  Department,
  LogEntry,
  ModuleDef,
  Notification,
  User,
  WebinarSeriesEntry,
} from "./types";

export const TODAY = "2026-08-19";

export const departments: Department[] = [
  {
    id: "research",
    name: "Research",
    code: "RSH",
    managerIds: ["u-mgr-research"],
    moduleKeys: ["daily-activity-log"],
  },
  {
    id: "data-management",
    name: "Data Management",
    code: "DTM",
    managerIds: ["u-mgr-data"],
    moduleKeys: [
      "weekly-meeting-report",
      "daily-meeting-attendance",
      "webinar-series-planner",
      "branch-wise-meeting-data",
    ],
  },
  {
    id: "brand-marketing",
    name: "Brand & Marketing",
    code: "BRM",
    managerIds: ["u-mgr-brand"],
    moduleKeys: [
      "zoom-link-management",
      "data-management-log",
      "call-log",
      "branding-activities",
      "social-media-log",
    ],
  },
];

export const modules: ModuleDef[] = [
  {
    key: "daily-activity-log",
    name: "Daily Activity Log",
    reference: "PRD 6.1",
    departmentId: "research",
    description:
      "One entry per working day describing research activity. Duplicate dates are blocked; entries stay editable until the manager approves.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "dayOfWeek", label: "Day of week", type: "auto", required: true, note: "Computed" },
      { key: "activity", label: "Activity description", type: "longtext", required: true },
      { key: "managerRemarks", label: "Manager remarks", type: "text", required: false },
    ],
    tableFields: ["date", "activity"],
  },
  {
    key: "weekly-meeting-report",
    name: "Weekly Meeting Report",
    reference: "PRD 6.2.1",
    departmentId: "data-management",
    description:
      "Weekly review cycle closing every Friday. Monthly and cumulative totals are computed by the system. Managers may correct counts before approving.",
    scope: "employee",
    cadence: "weekly",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "weekEnding", label: "Week ending (Friday)", type: "date", required: true },
      { key: "physicalMeetings", label: "Physical meetings", type: "integer", required: true },
      { key: "onlineMeetings", label: "Online meetings", type: "integer", required: true },
      { key: "calls", label: "Calls", type: "integer", required: true },
      { key: "serviceCalls", label: "Service calls", type: "integer", required: true },
      { key: "serviceMeetings", label: "Service meetings", type: "integer", required: true },
    ],
    tableFields: ["weekEnding", "physicalMeetings", "onlineMeetings", "calls"],
  },
  {
    key: "daily-meeting-attendance",
    name: "Daily Meeting Attendance",
    reference: "PRD 6.2.2",
    departmentId: "data-management",
    description:
      "Per-day attendance split by mode: physical, Zoom and Beyond sessions. Managers see daily and monthly totals per person and for the team.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "physical", label: "Physical meetings attended", type: "integer", required: true },
      { key: "zoom", label: "Zoom meetings attended", type: "integer", required: true },
      { key: "beyond", label: "Beyond sessions attended", type: "integer", required: true },
    ],
    tableFields: ["date", "physical", "zoom", "beyond"],
  },
  {
    key: "webinar-series-planner",
    name: "52 Week Webinar Series Planner",
    reference: "PRD 6.2.3",
    departmentId: "data-management",
    description:
      "Shared department calendar for the weekly B2C webinar series. Only managers and admins can create or edit entries; employees have read access and can submit topic suggestions.",
    scope: "department",
    cadence: "weekly",
    active: true,
    approvalRequired: false,
    createRoles: ["manager", "admin"],
    fields: [
      { key: "seriesNumber", label: "Series number", type: "auto", required: true },
      { key: "scheduledDate", label: "Scheduled date", type: "date", required: true },
      { key: "topic", label: "Topic title", type: "text", required: true },
      { key: "speaker", label: "Speaker name", type: "text", required: true },
      { key: "speakerDesignation", label: "Speaker designation", type: "text", required: true },
      {
        key: "mode",
        label: "Event mode",
        type: "select",
        required: true,
        options: ["Online", "Physical", "Hybrid"],
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Planned", "Confirmed", "Completed", "Cancelled"],
      },
      { key: "notes", label: "Notes", type: "longtext", required: false },
    ],
    tableFields: ["seriesNumber", "scheduledDate", "topic", "speaker", "status"],
  },
  {
    key: "branch-wise-meeting-data",
    name: "Branch-Wise Meeting Data",
    reference: "PRD 6.2.4",
    departmentId: "data-management",
    description: "Monthly meeting counts categorised by branch, used for regional reporting.",
    scope: "employee",
    cadence: "monthly",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "month", label: "Month", type: "month", required: true },
      { key: "branch", label: "Branch name", type: "text", required: true },
      {
        key: "meetingType",
        label: "Meeting type",
        type: "select",
        required: true,
        options: ["Physical", "Online", "Call"],
      },
      { key: "count", label: "Count", type: "integer", required: true },
    ],
    tableFields: ["month", "branch", "meetingType", "count"],
  },
  {
    key: "zoom-link-management",
    name: "Zoom / Webinar Link Management",
    reference: "PRD 6.3.1",
    departmentId: "brand-marketing",
    description:
      "Scheduling and distribution record for Zoom and webinar sessions, including attendance captured after the session.",
    scope: "employee",
    cadence: "ad-hoc",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "title", label: "Meeting title / purpose", type: "text", required: true },
      { key: "host", label: "Host / organiser", type: "text", required: true },
      { key: "scheduledDate", label: "Scheduled date", type: "date", required: true },
      { key: "scheduledTime", label: "Scheduled time", type: "time", required: true },
      { key: "duration", label: "Duration (minutes)", type: "integer", required: true },
      { key: "link", label: "Zoom link / meeting ID", type: "text", required: true },
      { key: "sentTo", label: "Sent to", type: "text", required: false },
      {
        key: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Scheduled", "Sent", "Completed", "Cancelled"],
      },
      { key: "notes", label: "Notes", type: "longtext", required: false },
      { key: "attendeeCount", label: "Attendee count", type: "integer", required: false },
    ],
    tableFields: ["scheduledDate", "title", "host", "status", "attendeeCount"],
  },
  {
    key: "data-management-log",
    name: "Data Management Log",
    reference: "PRD 6.3.2",
    departmentId: "brand-marketing",
    description: "Record of data sets handled, the action taken and verification state.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "task", label: "Task / data set description", type: "text", required: true },
      {
        key: "type",
        label: "Type",
        type: "select",
        required: true,
        options: ["Import", "Cleanup", "Validation", "Export", "Other"],
      },
      { key: "source", label: "Source / system", type: "text", required: true },
      { key: "action", label: "Action taken", type: "text", required: true },
      {
        key: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["In Progress", "Done", "Blocked"],
      },
      { key: "records", label: "Records handled", type: "integer", required: false },
      { key: "verifiedBy", label: "Verified by", type: "text", required: false },
      { key: "remarks", label: "Remarks", type: "text", required: false },
    ],
    tableFields: ["date", "task", "type", "status", "records"],
  },
  {
    key: "call-log",
    name: "Call Log",
    reference: "PRD 6.3.3",
    departmentId: "brand-marketing",
    description: "Outbound and inbound client calls with outcome and follow-up state.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "contact", label: "Company / contact name", type: "text", required: true },
      {
        key: "clientType",
        label: "Client type",
        type: "select",
        required: true,
        options: ["Prospect", "Existing", "Partner", "Vendor"],
      },
      { key: "phone", label: "Phone / email", type: "text", required: true },
      { key: "callTime", label: "Call time", type: "time", required: true },
      { key: "duration", label: "Duration (minutes)", type: "integer", required: true },
      { key: "purpose", label: "Purpose of call", type: "text", required: true },
      { key: "outcome", label: "Outcome / result", type: "text", required: true },
      { key: "followUp", label: "Follow-up required", type: "boolean", required: true },
      { key: "notes", label: "Notes", type: "longtext", required: false },
    ],
    tableFields: ["date", "contact", "clientType", "duration", "outcome"],
  },
  {
    key: "branding-activities",
    name: "Branding Activities Log",
    reference: "PRD 6.3.4",
    departmentId: "brand-marketing",
    description:
      "Creative and branding work with time spent captured as an actuals field. Can be linked to a campaign.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "title", label: "Activity / task title", type: "text", required: true },
      {
        key: "activityType",
        label: "Activity type",
        type: "select",
        required: true,
        options: ["Video", "Image", "Copy", "Campaign", "Other"],
      },
      { key: "platform", label: "Platform / medium", type: "text", required: true },
      {
        key: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["In Progress", "Done", "On Hold"],
      },
      { key: "hours", label: "Time spent (hours)", type: "decimal", required: true },
      { key: "deliverable", label: "Deliverable / output", type: "text", required: false },
      { key: "remarks", label: "Remarks", type: "text", required: false },
    ],
    tableFields: ["date", "title", "activityType", "hours", "status"],
  },
  {
    key: "social-media-log",
    name: "Social Media Management Log",
    reference: "PRD 6.3.5",
    departmentId: "brand-marketing",
    description:
      "Publishing record per post with platform, schedule and engagement captured after posting.",
    scope: "employee",
    cadence: "daily",
    active: true,
    approvalRequired: true,
    createRoles: ["employee", "manager", "admin"],
    fields: [
      { key: "date", label: "Date", type: "date", required: true },
      { key: "title", label: "Post / content title", type: "text", required: true },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        required: true,
        options: ["Instagram", "LinkedIn", "YouTube", "WhatsApp", "Other"],
      },
      {
        key: "contentType",
        label: "Content type",
        type: "select",
        required: true,
        options: ["Image", "Video", "Reel", "Story", "Text"],
      },
      { key: "scheduledTime", label: "Scheduled time", type: "time", required: false },
      {
        key: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Scheduled", "Posted", "Delayed", "Cancelled"],
      },
      { key: "likes", label: "Likes", type: "integer", required: false },
      { key: "comments", label: "Comments", type: "integer", required: false },
      { key: "reach", label: "Shares / reach", type: "integer", required: false },
      { key: "remarks", label: "Remarks", type: "text", required: false },
    ],
    tableFields: ["date", "title", "platform", "status", "reach"],
  },
];

export const users: User[] = [
  {
    id: "u-admin",
    name: "Ananya Rao",
    email: "ananya.rao@equitywala.com",
    role: "admin",
    departmentIds: ["research", "data-management", "brand-marketing"],
    designation: "System Administrator",
    active: true,
    lastLoginAt: "2026-08-19T08:12:00Z",
    avatarColor: "#B34138",
  },
  {
    id: "u-mgr-research",
    name: "Vikram Shah",
    email: "vikram.shah@equitywala.com",
    role: "manager",
    departmentIds: ["research"],
    designation: "Research Lead",
    active: true,
    lastLoginAt: "2026-08-19T07:40:00Z",
    avatarColor: "#3B6E8F",
  },
  {
    id: "u-mgr-data",
    name: "Sneha Kulkarni",
    email: "sneha.kulkarni@equitywala.com",
    role: "manager",
    departmentIds: ["data-management", "brand-marketing"],
    designation: "Data Management Head",
    active: true,
    lastLoginAt: "2026-08-18T15:05:00Z",
    avatarColor: "#4F7A55",
  },
  {
    id: "u-mgr-brand",
    name: "Rohit Menon",
    email: "rohit.menon@equitywala.com",
    role: "manager",
    departmentIds: ["brand-marketing"],
    designation: "Brand & Marketing Head",
    active: true,
    lastLoginAt: "2026-08-19T06:55:00Z",
    avatarColor: "#7A5A8F",
  },
  {
    id: "u-emp-1",
    name: "Priya Nair",
    email: "priya.nair@equitywala.com",
    role: "employee",
    departmentIds: ["research"],
    designation: "Research Analyst",
    active: true,
    lastLoginAt: "2026-08-19T09:02:00Z",
    avatarColor: "#B34138",
  },
  {
    id: "u-emp-2",
    name: "Arjun Desai",
    email: "arjun.desai@equitywala.com",
    role: "employee",
    departmentIds: ["research"],
    designation: "Research Associate",
    active: true,
    lastLoginAt: "2026-08-18T18:20:00Z",
    avatarColor: "#3B6E8F",
  },
  {
    id: "u-emp-3",
    name: "Meera Iyer",
    email: "meera.iyer@equitywala.com",
    role: "employee",
    departmentIds: ["data-management"],
    designation: "Data Executive",
    active: true,
    lastLoginAt: "2026-08-19T08:45:00Z",
    avatarColor: "#4F7A55",
  },
  {
    id: "u-emp-4",
    name: "Kabir Sethi",
    email: "kabir.sethi@equitywala.com",
    role: "employee",
    departmentIds: ["data-management"],
    designation: "Data Executive",
    active: true,
    lastLoginAt: "2026-08-17T11:10:00Z",
    avatarColor: "#8F6B3B",
  },
  {
    id: "u-emp-5",
    name: "Tara Bhatt",
    email: "tara.bhatt@equitywala.com",
    role: "employee",
    departmentIds: ["brand-marketing"],
    designation: "Brand Executive",
    active: true,
    lastLoginAt: "2026-08-19T07:15:00Z",
    avatarColor: "#7A5A8F",
  },
  {
    id: "u-emp-6",
    name: "Nikhil Verma",
    email: "nikhil.verma@equitywala.com",
    role: "employee",
    departmentIds: ["brand-marketing"],
    designation: "Social Media Executive",
    active: false,
    lastLoginAt: "2026-07-29T13:30:00Z",
    avatarColor: "#5F6368",
  },
];

export const campaigns: Campaign[] = [
  {
    id: "c-1",
    name: "August Investor Awareness",
    departmentId: "brand-marketing",
    ownerId: "u-emp-5",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    platform: "Instagram / LinkedIn",
    status: "Active",
    description: "Monthly awareness push around the weekly webinar series.",
  },
  {
    id: "c-2",
    name: "Beyond Platform Launch",
    departmentId: "brand-marketing",
    ownerId: "u-mgr-brand",
    startDate: "2026-07-05",
    endDate: "2026-07-31",
    platform: "YouTube / WhatsApp",
    status: "Completed",
    description: "Launch communication for the Beyond webinar platform.",
  },
];

export const webinarSeries: WebinarSeriesEntry[] = [
  {
    id: "w-31",
    seriesNumber: 31,
    scheduledDate: "2026-08-21",
    topic: "Reading a balance sheet without a finance degree",
    speaker: "Sneha Kulkarni",
    speakerDesignation: "Data Management Head, 11 years",
    mode: "Online",
    status: "Confirmed",
  },
  {
    id: "w-32",
    seriesNumber: 32,
    scheduledDate: "2026-08-28",
    topic: "Sector rotation in a rate-cut cycle",
    speaker: "Vikram Shah",
    speakerDesignation: "Research Lead, 14 years",
    mode: "Hybrid",
    status: "Planned",
  },
  {
    id: "w-33",
    seriesNumber: 33,
    scheduledDate: "2026-09-04",
    topic: "Building a first SIP portfolio",
    speaker: "Priya Nair",
    speakerDesignation: "Research Analyst, 5 years",
    mode: "Online",
    status: "Planned",
  },
  {
    id: "w-30",
    seriesNumber: 30,
    scheduledDate: "2026-08-14",
    topic: "Risk management for active traders",
    speaker: "Rohit Menon",
    speakerDesignation: "Brand & Marketing Head, 9 years",
    mode: "Online",
    status: "Completed",
  },
];

function iso(date: string, time = "09:30") {
  return `${date}T${time}:00Z`;
}

export const logEntries: LogEntry[] = [
  {
    id: "E-1042",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    authorId: "u-emp-1",
    entryDate: "2026-08-19",
    status: "draft",
    values: {
      date: "2026-08-19",
      dayOfWeek: "Wednesday",
      activity:
        "Started the quarterly review of mid-cap coverage. Pending: pricing model update for two names.",
    },
    createdAt: iso("2026-08-19", "09:20"),
    updatedAt: iso("2026-08-19", "09:20"),
    comments: [],
  },
  {
    id: "E-1039",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    authorId: "u-emp-1",
    entryDate: "2026-08-18",
    status: "rejected",
    values: {
      date: "2026-08-18",
      dayOfWeek: "Tuesday",
      activity: "Client call notes and screening.",
    },
    createdAt: iso("2026-08-18", "18:05"),
    updatedAt: iso("2026-08-18", "18:05"),
    submittedAt: iso("2026-08-18", "18:10"),
    decidedAt: iso("2026-08-19", "07:44"),
    decidedById: "u-mgr-research",
    managerRemarks:
      "Add the names screened and the outcome of the client call. One line is not enough for the monthly report.",
    comments: [
      {
        id: "cm-1",
        authorId: "u-mgr-research",
        body: "@Priya Nair please resubmit with the screening list attached in the description.",
        createdAt: iso("2026-08-19", "07:45"),
        mentions: ["u-emp-1"],
      },
    ],
  },
  {
    id: "E-1035",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    authorId: "u-emp-1",
    entryDate: "2026-08-17",
    status: "approved",
    values: {
      date: "2026-08-17",
      dayOfWeek: "Monday",
      activity:
        "Published the weekly sector note. Reviewed three earnings transcripts and updated the coverage tracker.",
    },
    createdAt: iso("2026-08-17", "17:50"),
    updatedAt: iso("2026-08-17", "17:50"),
    submittedAt: iso("2026-08-17", "17:55"),
    decidedAt: iso("2026-08-18", "09:10"),
    decidedById: "u-mgr-research",
    comments: [],
  },
  {
    id: "E-1044",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    authorId: "u-emp-2",
    entryDate: "2026-08-19",
    status: "submitted",
    values: {
      date: "2026-08-19",
      dayOfWeek: "Wednesday",
      activity:
        "Compiled the FII/DII flow dataset for July and cross-checked it against exchange filings.",
    },
    createdAt: iso("2026-08-19", "08:30"),
    updatedAt: iso("2026-08-19", "08:30"),
    submittedAt: iso("2026-08-19", "08:35"),
    comments: [],
  },
  {
    id: "E-1045",
    moduleKey: "weekly-meeting-report",
    departmentId: "data-management",
    authorId: "u-emp-3",
    entryDate: "2026-08-14",
    status: "submitted",
    values: {
      weekEnding: "2026-08-14",
      physicalMeetings: 6,
      onlineMeetings: 11,
      calls: 48,
      serviceCalls: 12,
      serviceMeetings: 4,
    },
    createdAt: iso("2026-08-14", "17:10"),
    updatedAt: iso("2026-08-14", "17:10"),
    submittedAt: iso("2026-08-14", "17:12"),
    comments: [],
  },
  {
    id: "E-1046",
    moduleKey: "daily-meeting-attendance",
    departmentId: "data-management",
    authorId: "u-emp-3",
    entryDate: "2026-08-18",
    status: "approved",
    values: { date: "2026-08-18", physical: 2, zoom: 3, beyond: 1 },
    createdAt: iso("2026-08-18", "18:40"),
    updatedAt: iso("2026-08-18", "18:40"),
    submittedAt: iso("2026-08-18", "18:42"),
    decidedAt: iso("2026-08-19", "08:05"),
    decidedById: "u-mgr-data",
    comments: [],
  },
  {
    id: "E-1047",
    moduleKey: "daily-meeting-attendance",
    departmentId: "data-management",
    authorId: "u-emp-4",
    entryDate: "2026-08-18",
    status: "submitted",
    values: { date: "2026-08-18", physical: 1, zoom: 5, beyond: 0 },
    createdAt: iso("2026-08-18", "19:02"),
    updatedAt: iso("2026-08-18", "19:02"),
    submittedAt: iso("2026-08-18", "19:03"),
    comments: [],
  },
  {
    id: "E-1048",
    moduleKey: "branch-wise-meeting-data",
    departmentId: "data-management",
    authorId: "u-emp-4",
    entryDate: "2026-07-31",
    status: "approved",
    values: { month: "2026-07", branch: "Pune", meetingType: "Physical", count: 34 },
    createdAt: iso("2026-08-01", "10:00"),
    updatedAt: iso("2026-08-01", "10:00"),
    submittedAt: iso("2026-08-01", "10:05"),
    decidedAt: iso("2026-08-02", "11:15"),
    decidedById: "u-mgr-data",
    editedByManager: true,
    comments: [],
  },
  {
    id: "E-1049",
    moduleKey: "social-media-log",
    departmentId: "brand-marketing",
    authorId: "u-emp-5",
    entryDate: "2026-08-19",
    status: "submitted",
    campaignId: "c-1",
    values: {
      date: "2026-08-19",
      title: "Webinar 31 teaser reel",
      platform: "Instagram",
      contentType: "Reel",
      scheduledTime: "18:30",
      status: "Posted",
      likes: 412,
      comments: 27,
      reach: 8600,
    },
    createdAt: iso("2026-08-19", "07:05"),
    updatedAt: iso("2026-08-19", "07:05"),
    submittedAt: iso("2026-08-19", "07:06"),
    comments: [],
  },
  {
    id: "E-1050",
    moduleKey: "branding-activities",
    departmentId: "brand-marketing",
    authorId: "u-emp-5",
    entryDate: "2026-08-18",
    status: "approved",
    campaignId: "c-1",
    values: {
      date: "2026-08-18",
      title: "Series 31 creative set",
      activityType: "Image",
      platform: "Instagram",
      status: "Done",
      hours: 5.5,
      deliverable: "Six static creatives and one carousel",
    },
    createdAt: iso("2026-08-18", "16:20"),
    updatedAt: iso("2026-08-18", "16:20"),
    submittedAt: iso("2026-08-18", "16:25"),
    decidedAt: iso("2026-08-19", "06:58"),
    decidedById: "u-mgr-brand",
    comments: [],
  },
  {
    id: "E-1051",
    moduleKey: "call-log",
    departmentId: "brand-marketing",
    authorId: "u-emp-5",
    entryDate: "2026-08-19",
    status: "draft",
    values: {
      date: "2026-08-19",
      contact: "Sunrise Capital",
      clientType: "Prospect",
      phone: "+91 98200 11234",
      callTime: "11:15",
      duration: 18,
      purpose: "Webinar sponsorship discussion",
      outcome: "",
      followUp: true,
    },
    createdAt: iso("2026-08-19", "11:35"),
    updatedAt: iso("2026-08-19", "11:35"),
    comments: [],
  },
  {
    id: "E-1052",
    moduleKey: "zoom-link-management",
    departmentId: "brand-marketing",
    authorId: "u-emp-5",
    entryDate: "2026-08-17",
    status: "submitted",
    values: {
      date: "2026-08-17",
      title: "Series 31 webinar",
      host: "Sneha Kulkarni",
      scheduledDate: "2026-08-21",
      scheduledTime: "19:00",
      duration: 60,
      link: "eqw-931-4412",
      sentTo: "B2C list, August cohort",
      status: "Scheduled",
      attendeeCount: 0,
    },
    createdAt: iso("2026-08-17", "12:00"),
    updatedAt: iso("2026-08-17", "12:00"),
    submittedAt: iso("2026-08-17", "12:02"),
    comments: [],
  },
  {
    id: "E-1053",
    moduleKey: "data-management-log",
    departmentId: "brand-marketing",
    authorId: "u-emp-6",
    entryDate: "2026-08-12",
    status: "rejected",
    values: {
      date: "2026-08-12",
      task: "August cohort contact cleanup",
      type: "Cleanup",
      source: "CRM export",
      action: "Removed duplicates",
      status: "Done",
      records: 1240,
      remarks: "",
    },
    createdAt: iso("2026-08-12", "15:00"),
    updatedAt: iso("2026-08-12", "15:00"),
    submittedAt: iso("2026-08-12", "15:04"),
    decidedAt: iso("2026-08-13", "09:20"),
    decidedById: "u-mgr-brand",
    managerRemarks: "Record the verification owner before this can be approved.",
    comments: [],
  },
  {
    id: "E-1054",
    moduleKey: "weekly-meeting-report",
    departmentId: "data-management",
    authorId: "u-emp-4",
    entryDate: "2026-08-14",
    status: "submitted",
    values: {
      weekEnding: "2026-08-14",
      physicalMeetings: 3,
      onlineMeetings: 9,
      calls: 37,
      serviceCalls: 8,
      serviceMeetings: 2,
    },
    createdAt: iso("2026-08-14", "18:00"),
    updatedAt: iso("2026-08-14", "18:00"),
    submittedAt: iso("2026-08-14", "18:01"),
    comments: [],
  },
  {
    id: "E-1055",
    moduleKey: "social-media-log",
    departmentId: "brand-marketing",
    authorId: "u-emp-6",
    entryDate: "2026-08-18",
    status: "submitted",
    campaignId: "c-1",
    values: {
      date: "2026-08-18",
      title: "Investor myth-busting carousel",
      platform: "LinkedIn",
      contentType: "Image",
      scheduledTime: "10:00",
      status: "Posted",
      likes: 188,
      comments: 14,
      reach: 5200,
    },
    createdAt: iso("2026-08-18", "10:30"),
    updatedAt: iso("2026-08-18", "10:30"),
    submittedAt: iso("2026-08-18", "10:31"),
    comments: [],
  },
];

export const notifications: Notification[] = [
  {
    id: "n-1",
    kind: "rejected",
    recipientId: "u-emp-1",
    title: "Daily Activity Log for 18 Aug was rejected",
    body: "Vikram Shah returned the entry: add the names screened and the outcome of the client call.",
    createdAt: iso("2026-08-19", "07:44"),
    read: false,
    entryId: "E-1039",
  },
  {
    id: "n-2",
    kind: "comment",
    recipientId: "u-emp-1",
    title: "Vikram Shah mentioned you",
    body: "@Priya Nair please resubmit with the screening list attached in the description.",
    createdAt: iso("2026-08-19", "07:45"),
    read: false,
    entryId: "E-1039",
  },
  {
    id: "n-3",
    kind: "reminder",
    recipientId: "u-emp-1",
    title: "Today's log is still a draft",
    body: "Submit the Daily Activity Log for 19 Aug before the 6:00 PM cutoff.",
    createdAt: iso("2026-08-19", "09:00"),
    read: false,
    entryId: "E-1042",
  },
  {
    id: "n-4",
    kind: "approved",
    recipientId: "u-emp-1",
    title: "Daily Activity Log for 17 Aug was approved",
    body: "Approved by Vikram Shah.",
    createdAt: iso("2026-08-18", "09:10"),
    read: true,
    entryId: "E-1035",
  },
  {
    id: "n-5",
    kind: "submission",
    recipientId: "u-mgr-research",
    title: "Arjun Desai submitted a Daily Activity Log",
    body: "Entry E-1044 for 19 Aug is waiting for review.",
    createdAt: iso("2026-08-19", "08:35"),
    read: false,
    entryId: "E-1044",
  },
  {
    id: "n-6",
    kind: "reminder",
    recipientId: "u-mgr-research",
    title: "1 entry pending for more than 24 hours",
    body: "Oldest pending submission: E-1044, submitted 19 Aug 08:35.",
    createdAt: iso("2026-08-19", "09:00"),
    read: false,
  },
  {
    id: "n-7",
    kind: "account",
    recipientId: "u-admin",
    title: "Nikhil Verma has not logged in for 21 days",
    body: "Account is currently deactivated. Review access in User Management.",
    createdAt: iso("2026-08-19", "06:00"),
    read: false,
  },
  {
    id: "n-8",
    kind: "submission",
    recipientId: "u-admin",
    title: "6 entries pending review across departments",
    body: "Data Management: 3, Brand & Marketing: 2, Research: 1.",
    createdAt: iso("2026-08-19", "09:00"),
    read: true,
  },
];

export const activity: ActivityItem[] = [
  {
    id: "a-1",
    action: "submitted",
    actorId: "u-emp-2",
    entryId: "E-1044",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    createdAt: iso("2026-08-19", "08:35"),
  },
  {
    id: "a-2",
    action: "rejected",
    actorId: "u-mgr-research",
    entryId: "E-1039",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    createdAt: iso("2026-08-19", "07:44"),
    detail: "Insufficient detail in activity description",
  },
  {
    id: "a-3",
    action: "commented",
    actorId: "u-mgr-research",
    entryId: "E-1039",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    createdAt: iso("2026-08-19", "07:45"),
  },
  {
    id: "a-4",
    action: "approved",
    actorId: "u-mgr-brand",
    entryId: "E-1050",
    moduleKey: "branding-activities",
    departmentId: "brand-marketing",
    createdAt: iso("2026-08-19", "06:58"),
  },
  {
    id: "a-5",
    action: "submitted",
    actorId: "u-emp-5",
    entryId: "E-1049",
    moduleKey: "social-media-log",
    departmentId: "brand-marketing",
    createdAt: iso("2026-08-19", "07:06"),
  },
  {
    id: "a-6",
    action: "approved",
    actorId: "u-mgr-data",
    entryId: "E-1046",
    moduleKey: "daily-meeting-attendance",
    departmentId: "data-management",
    createdAt: iso("2026-08-19", "08:05"),
  },
  {
    id: "a-7",
    action: "submitted",
    actorId: "u-emp-4",
    entryId: "E-1047",
    moduleKey: "daily-meeting-attendance",
    departmentId: "data-management",
    createdAt: iso("2026-08-18", "19:03"),
  },
  {
    id: "a-8",
    action: "created",
    actorId: "u-emp-1",
    entryId: "E-1042",
    moduleKey: "daily-activity-log",
    departmentId: "research",
    createdAt: iso("2026-08-19", "09:20"),
  },
];

export const auditRecords: AuditRecord[] = [
  {
    id: "au-1",
    actorId: "u-mgr-data",
    action: "edited",
    entity: "Log Entry",
    entityId: "E-1048",
    departmentId: "data-management",
    createdAt: iso("2026-08-02", "11:12"),
    diff: [{ field: "count", from: "31", to: "34" }],
  },
  {
    id: "au-2",
    actorId: "u-mgr-data",
    action: "approved",
    entity: "Log Entry",
    entityId: "E-1048",
    departmentId: "data-management",
    createdAt: iso("2026-08-02", "11:15"),
  },
  {
    id: "au-3",
    actorId: "u-admin",
    action: "deactivated",
    entity: "User",
    entityId: "u-emp-6",
    createdAt: iso("2026-07-30", "10:02"),
    diff: [{ field: "active", from: "true", to: "false" }],
  },
  {
    id: "au-4",
    actorId: "u-mgr-research",
    action: "rejected",
    entity: "Log Entry",
    entityId: "E-1039",
    departmentId: "research",
    createdAt: iso("2026-08-19", "07:44"),
  },
  {
    id: "au-5",
    actorId: "u-admin",
    action: "exported",
    entity: "Monthly department report",
    entityId: "brand-marketing/2026-07",
    departmentId: "brand-marketing",
    createdAt: iso("2026-08-03", "09:30"),
  },
  {
    id: "au-6",
    actorId: "u-admin",
    action: "role_changed",
    entity: "User",
    entityId: "u-mgr-data",
    createdAt: iso("2026-06-11", "14:20"),
    diff: [{ field: "departments", from: "data-management", to: "data-management, brand-marketing" }],
  },
];

export function getUser(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function userName(id: string): string {
  return getUser(id)?.name ?? "Unknown user";
}

export function getModule(key: string): ModuleDef | undefined {
  return modules.find((m) => m.key === key);
}

export function moduleName(key: string): string {
  return getModule(key)?.name ?? key;
}

export function getDepartment(id: string): Department | undefined {
  return departments.find((d) => d.id === id);
}

export function departmentName(id: string): string {
  return getDepartment(id)?.name ?? id;
}
